### PR TITLE
Greg/trace allocation

### PR DESCRIPTION
**Pull request by gregory38**
This PR contains 2 parts.

    a very basic system to trace C alloc/free call
    various C memory leak fixes.

I open the PR to discuss it a bit

    tracing system
        do we want file or a small keyword. I did the latter initially, but it doesn't play nice with STB. So I added macro for STB. But we might want to ditch keyword and goes with __FILE__ macro for everyone.
        So far the tracing system is very basic (and can potentially be enough for small test)
            it would love a script to check the nb of free vs nb of alloc
            maybe there are external lib that can be plugged that will handle the leak check for us at exit. I didn't investigate it.
            side note: running valgrind on a mix of Go/C/Lua doesn't seem to be useful (false positive, no trace symbol)
    memory leak
        need careful review
        need a test application (arsene doesn't stress lutro enough)

### CODE REVIEW

**Comment by kivutar** [comment]
I have no opinion about the tracing system to use. I'll go with your choice.

About a test app, what should it do? Play a lot of random sound effects?

**Comment by gregory38** [comment]
So, I used the `__FILE__` macro everywhere for consistency. I added a basic counter. If counter doesn't reach 0 at the end something is bad. 

```
About a test app, what should it do? Play a lot of random sound effects?
```
Fun fact, I fixed leak everywhere but not on the audio side. I think it would be nice to have a basic app that try several font, reload image asset, audio too, canvas. But I guess playing random game can be done too, store the trace in a file, if counter isn't 0, time to do a script to count per address (`sort` will surely help).

**Review by kivutar — APPROVED** [review]

**Comment by kivutar** [comment]
There are sample programs in the test folder

**Comment by kivutar** [comment]
Can you do the Makefile part?

**Pull request merged**
